[package]
name = "yukkios_6_6_6_inet3"
version = "6.6.6"
edition = "2021"

[lib]
name = "yukkios_6_6_6_inet3"
path = "src/lib.rs"

[[bin]]
name = "yukki_core_node"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full", "process"] }
tokio-tungstenite = "0.20"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.6", features = ["v4", "serde"] }
x25519-dalek = { version = "2.0", features = ["static_secrets"] }
chacha20poly1305 = "0.10"
rand_core = { version = "0.6", features = ["getrandom", "std"] }
wasmtime = "14.0"
zeroize = { version = "1.6", features = ["derive"] }

[build-dependencies]
cc = "1.0"
